import type { Metadata } from "next";
import { AppShell } from "@/components/AppShell";
import { PageHeader, StatusBadge } from "@/components/PageHeader";
import { getCurrentUser } from "@/lib/auth";
import { requireLicensedPermission } from "@/lib/data/licensing-repository";
import { getComplianceSnapshot } from "@/lib/data/compliance-repository";
import { formatDateTime, formatMoney } from "@/lib/format";

export const metadata: Metadata = { title: "Audit cases and risk" };
export const dynamic = "force-dynamic";

export default async function CasesPage() {
  const user = await getCurrentUser();
  await requireLicensedPermission(user, "cases:manage", { operationClass: "READ" });
  const data = await getComplianceSnapshot(user);
  return <AppShell active="cases" permission="cases:manage">
    <PageHeader eyebrow="Compliance operations" title="Evidence-led audit cases and advisory risk" description="Rules may prioritise human review, but cannot create an adverse tax decision. Officers must preserve evidence, explain findings and record a reviewable decision." />
    <section className="metric-grid"><article className="metric"><div className="metric-top"><span className="metric-label">Open cases</span><span className="metric-icon">C</span></div><div className="metric-value">{data.cases.filter((item) => item.status !== "CLOSED").length}</div><div className="metric-foot">Controlled officer work queue</div></article><article className="metric"><div className="metric-top"><span className="metric-label">Preliminary findings</span><span className="metric-icon">F</span></div><div className="metric-value">{data.findings.filter((item) => item.status === "PRELIMINARY").length}</div><div className="metric-foot">Not final assessments</div></article><article className="metric"><div className="metric-top"><span className="metric-label">Risk indicators</span><span className="metric-icon">R</span></div><div className="metric-value">{data.risks.length}</div><div className="metric-foot">Explainable, advisory-only signals</div></article><article className="metric"><div className="metric-top"><span className="metric-label">Critical review</span><span className="metric-icon">!</span></div><div className="metric-value">{data.risks.filter((item) => item.severity === "CRITICAL" && item.status !== "CLOSED").length}</div><div className="metric-foot warning">Human review required</div></article></section>
    <section className="panel"><div className="panel-head"><div><h2 className="panel-title">Audit case register</h2><div className="panel-meta">National compliance scope</div></div></div><div className="table-wrap"><table><thead><tr><th>Case</th><th>Taxpayer</th><th>Type</th><th>Title</th><th>Risk</th><th>Status</th><th>Opened</th></tr></thead><tbody>{data.cases.map((item) => <tr key={String(item.id)}><td><strong>{String(item.case_number)}</strong><div className="mono muted">{String(item.id)}</div></td><td>{String(item.legal_name ?? item.taxpayer_id)}<div className="mono muted">{String(item.vat_number ?? "")}</div></td><td>{String(item.case_type).replaceAll("_", " ")}</td><td>{String(item.title)}<div className="muted">{String(item.opening_reason)}</div></td><td><StatusBadge value={String(item.risk_tier)} /></td><td><StatusBadge value={String(item.status)} /></td><td>{formatDateTime(String(item.opened_at))}</td></tr>)}</tbody></table></div></section>
    <div className="grid-equal" style={{ marginTop: 20 }}><section className="panel"><div className="panel-head"><div><h2 className="panel-title">Findings</h2><div className="panel-meta">Legal references remain empty until authority-confirmed</div></div></div><div className="table-wrap"><table><thead><tr><th>Finding</th><th>Case</th><th>Amount</th><th>Legal reference</th><th>Status</th></tr></thead><tbody>{data.findings.map((item) => <tr key={String(item.id)}><td><strong>{String(item.title)}</strong><div className="muted">{String(item.description)}</div></td><td>{String(item.case_number ?? item.audit_case_id)}</td><td className="amount">{formatMoney(Number(item.amount_cents), String(item.currency))}</td><td>{String(item.legal_reference ?? "Awaiting authoritative mapping")}</td><td><StatusBadge value={String(item.status)} /></td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-head"><div><h2 className="panel-title">Advisory risk indicators</h2><div className="panel-meta">No automated adverse decision effect</div></div></div><div className="table-wrap"><table><thead><tr><th>Indicator</th><th>Subject</th><th>Score</th><th>Rationale</th><th>Effect</th><th>Status</th></tr></thead><tbody>{data.risks.map((item) => <tr key={String(item.id)}><td><strong>{String(item.indicator_code).replaceAll("_", " ")}</strong><div>{String(item.legal_name ?? item.taxpayer_id)}</div></td><td>{String(item.subject_type)}<div className="mono muted">{String(item.subject_id)}</div></td><td>{(Number(item.score_bps) / 100).toFixed(2)}%</td><td>{String(item.rationale)}</td><td><StatusBadge value={String(item.decision_effect)} /></td><td><StatusBadge value={String(item.status)} /></td></tr>)}</tbody></table></div></section></div>
  </AppShell>;
}
