import type { Metadata } from "next";
import { AppShell } from "@/components/AppShell";
import { PageHeader, StatusBadge } from "@/components/PageHeader";
import { getCurrentUser } from "@/lib/auth";
import { requireLicensedPermission } from "@/lib/data/licensing-repository";
import { getComplianceSnapshot } from "@/lib/data/compliance-repository";
import { formatDateTime, formatMoney } from "@/lib/format";

export const metadata: Metadata = { title: "Compliance and disputes" };
export const dynamic = "force-dynamic";

export default async function CompliancePage() {
  const user = await getCurrentUser();
  await requireLicensedPermission(user, "compliance:read", { operationClass: "READ" });
  const data = await getComplianceSnapshot(user);
  return <AppShell active="compliance" permission="compliance:read">
    <PageHeader eyebrow="Taxpayer governance" title="Obligations, disputes and secure communications" description="Taxpayer instructions, delegations, notices and dispute rights are recorded as governed evidence. VAT-MSA does not replace the statutory account maintained by ITAS." />
    <section className="metric-grid">
      <article className="metric"><div className="metric-top"><span className="metric-label">Open obligations</span><span className="metric-icon">O</span></div><div className="metric-value">{data.obligations.filter((item) => !["SATISFIED", "CANCELLED"].includes(String(item.status))).length}</div><div className="metric-foot">Source-labelled obligation projections</div></article>
      <article className="metric"><div className="metric-top"><span className="metric-label">Active disputes</span><span className="metric-icon">D</span></div><div className="metric-value">{data.disputes.filter((item) => !["DECIDED", "WITHDRAWN"].includes(String(item.status))).length}</div><div className="metric-foot">Independent review rights preserved</div></article>
      <article className="metric"><div className="metric-top"><span className="metric-label">Unread notices</span><span className="metric-icon">N</span></div><div className="metric-value">{data.notifications.filter((item) => item.status === "UNREAD").length}</div><div className="metric-foot">Secure portal notification queue</div></article>
      <article className="metric"><div className="metric-top"><span className="metric-label">Active consents</span><span className="metric-icon">C</span></div><div className="metric-value">{data.consents.filter((item) => item.status === "ACTIVE").length}</div><div className="metric-foot">Purpose and validity are explicit</div></article>
    </section>
    <div className="grid-equal">
      <section className="panel"><div className="panel-head"><div><h2 className="panel-title">Tax obligations</h2><div className="panel-meta">Authoritative source is always displayed</div></div></div><div className="table-wrap"><table><thead><tr><th>Taxpayer</th><th>Obligation</th><th>Period</th><th>Due</th><th>Amount</th><th>Source</th><th>Status</th></tr></thead><tbody>{data.obligations.map((item) => <tr key={String(item.id)}><td>{String(item.legal_name ?? item.taxpayer_id)}</td><td>{String(item.obligation_type).replaceAll("_", " ")}</td><td>{String(item.period_code)}</td><td>{String(item.due_date)}</td><td className="amount">{formatMoney(Number(item.amount_cents), String(item.currency))}</td><td>{String(item.source_system)}</td><td><StatusBadge value={String(item.status)} /></td></tr>)}</tbody></table></div></section>
      <section className="panel"><div className="panel-head"><div><h2 className="panel-title">Dispute register</h2><div className="panel-meta">Filing is immutable; decisions append later</div></div></div><div className="table-wrap"><table><thead><tr><th>Dispute</th><th>Taxpayer</th><th>Resource</th><th>Amount</th><th>Filed</th><th>Status</th></tr></thead><tbody>{data.disputes.map((item) => <tr key={String(item.id)}><td><strong>{String(item.dispute_number)}</strong></td><td>{String(item.legal_name ?? item.taxpayer_id)}</td><td>{String(item.disputed_resource_type).replaceAll("_", " ")}<div className="mono muted">{String(item.disputed_resource_id)}</div></td><td className="amount">{formatMoney(Number(item.disputed_amount_cents), String(item.currency))}</td><td>{formatDateTime(String(item.filed_at))}</td><td><StatusBadge value={String(item.status)} /></td></tr>)}</tbody></table></div></section>
    </div>
    <div className="grid-equal" style={{ marginTop: 20 }}><section className="panel"><div className="panel-head"><div><h2 className="panel-title">Secure communications</h2><div className="panel-meta">Summaries only; protected content remains classified</div></div></div><div className="table-wrap"><table><thead><tr><th>Channel</th><th>Direction</th><th>Subject</th><th>Related record</th><th>Status</th><th>Occurred</th></tr></thead><tbody>{data.communications.map((item) => <tr key={String(item.id)}><td>{String(item.channel)}</td><td>{String(item.direction)}</td><td><strong>{String(item.subject)}</strong><div className="muted">{String(item.content_summary)}</div></td><td>{String(item.related_resource_type ?? "—")}<div className="mono muted">{String(item.related_resource_id ?? "")}</div></td><td><StatusBadge value={String(item.status)} /></td><td>{formatDateTime(String(item.occurred_at))}</td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-head"><div><h2 className="panel-title">Consent and delegation</h2><div className="panel-meta">Purpose-bound access with expiry</div></div></div><div className="table-wrap"><table><thead><tr><th>Type</th><th>Purpose / scope</th><th>Valid from</th><th>Valid to</th><th>Status</th></tr></thead><tbody>{data.consents.map((item) => <tr key={String(item.id)}><td>Consent</td><td>{String(item.purpose)}<div className="mono muted">{String(item.data_categories)}</div></td><td>{String(item.valid_from)}</td><td>{String(item.valid_to ?? "Open")}</td><td><StatusBadge value={String(item.status)} /></td></tr>)}{data.delegations.map((item) => <tr key={String(item.id)}><td>Delegation</td><td className="mono">{String(item.scopes)}</td><td>{String(item.valid_from)}</td><td>{String(item.valid_to ?? "Open")}</td><td><StatusBadge value={String(item.status)} /></td></tr>)}</tbody></table></div></section></div>
  </AppShell>;
}
