-- VAT-MSA reference schema (PostgreSQL 16+)
-- Architecture baseline: production migrations must add partition management,
-- RLS policies, grants, audit triggers and organisation-approved retention controls.
-- UUIDs are generated by the application as UUIDv7 unless an approved database
-- function is installed.

create schema if not exists vat_msa;
set search_path = vat_msa, public;

create table taxpayer (
    taxpayer_id             uuid primary key,
    legal_name              text not null,
    trading_name            text,
    taxpayer_type           text not null,
    vat_status              text not null check (vat_status in ('REGISTERED','SUSPENDED','DEREGISTERED','NOT_REGISTERED','UNKNOWN')),
    registration_date       date,
    deregistration_date     date,
    return_frequency        text,
    master_source           text not null default 'ITAS',
    source_version          text,
    status                  text not null default 'ACTIVE' check (status in ('ACTIVE','INACTIVE','MERGED','UNDER_REVIEW')),
    created_at              timestamptz not null,
    updated_at              timestamptz not null,
    row_version             bigint not null default 1
);

create table taxpayer_identifier (
    taxpayer_identifier_id  uuid primary key,
    taxpayer_id             uuid not null references taxpayer(taxpayer_id),
    identifier_type         text not null check (identifier_type in ('VAT_NUMBER','TIN','COMPANY_NUMBER','NATIONAL_ID','PASSPORT','OTHER')),
    identifier_value_token  text not null,
    identifier_value_masked text not null,
    country_code            char(2),
    valid_from              timestamptz not null,
    valid_to                timestamptz,
    is_primary              boolean not null default false,
    verification_status     text not null default 'UNVERIFIED' check (verification_status in ('UNVERIFIED','VERIFIED','REJECTED')),
    created_at              timestamptz not null,
    unique (identifier_type, identifier_value_token, valid_from)
);

create index taxpayer_identifier_lookup_idx
    on taxpayer_identifier(identifier_type, identifier_value_token)
    where valid_to is null;

create table source_system (
    source_system_id        uuid primary key,
    system_code             text not null unique,
    owner_taxpayer_id       uuid references taxpayer(taxpayer_id),
    channel_type            text not null check (channel_type in ('POS','ERP','ACCOUNTING','PORTAL','DESKTOP','GOVERNMENT','BATCH')),
    trust_status            text not null default 'PENDING' check (trust_status in ('PENDING','ACTIVE','SUSPENDED','REVOKED')),
    schema_version          text not null,
    created_at              timestamptz not null,
    updated_at              timestamptz not null
);

create table invoice (
    invoice_id              uuid primary key,
    supplier_taxpayer_id    uuid not null references taxpayer(taxpayer_id),
    customer_taxpayer_id    uuid references taxpayer(taxpayer_id),
    source_system_id        uuid not null references source_system(source_system_id),
    source_document_id      text not null,
    document_type           text not null check (document_type in ('TAX_INVOICE','SIMPLIFIED_TAX_INVOICE','CREDIT_NOTE','DEBIT_NOTE','SELF_BILLED_INVOICE')),
    invoice_number          text not null,
    issue_date              date not null,
    issue_time              time with time zone,
    tax_point_date          date,
    currency_code           char(3) not null,
    exchange_rate           numeric(20,8),
    line_net_amount         numeric(20,6) not null,
    tax_exclusive_amount    numeric(20,6) not null,
    tax_amount              numeric(20,6) not null,
    tax_inclusive_amount    numeric(20,6) not null,
    payable_amount          numeric(20,6) not null,
    original_invoice_id     uuid references invoice(invoice_id),
    status                  text not null check (status in ('RECEIVED','VALIDATING','REJECTED','ACCEPTED','CERTIFIED','POSTED','MATCHED','EXCEPTION','REVERSED')),
    schema_version          text not null,
    rule_set_version        text,
    canonical_hash          bytea not null,
    received_at             timestamptz not null,
    accepted_at             timestamptz,
    certified_at            timestamptz,
    created_at              timestamptz not null,
    unique (source_system_id, source_document_id),
    unique (supplier_taxpayer_id, invoice_number, issue_date, document_type),
    unique (canonical_hash)
);

create index invoice_supplier_period_idx on invoice(supplier_taxpayer_id, issue_date, status);
create index invoice_customer_period_idx on invoice(customer_taxpayer_id, issue_date, status);

create table invoice_line (
    invoice_line_id         uuid primary key,
    invoice_id              uuid not null references invoice(invoice_id),
    line_number             integer not null check (line_number > 0),
    item_code               text,
    description             text not null,
    quantity                numeric(20,8) not null,
    unit_code               text not null,
    unit_price              numeric(20,6) not null,
    gross_amount            numeric(20,6),
    discount_amount         numeric(20,6),
    net_amount              numeric(20,6) not null,
    tax_category            text not null,
    tax_rate                numeric(9,6) not null,
    taxable_amount          numeric(20,6) not null,
    tax_amount              numeric(20,6) not null,
    rule_reference          text,
    created_at              timestamptz not null,
    unique (invoice_id, line_number)
);

create table invoice_tax_summary (
    invoice_tax_summary_id  uuid primary key,
    invoice_id              uuid not null references invoice(invoice_id),
    tax_category            text not null,
    tax_rate                numeric(9,6) not null,
    taxable_amount          numeric(20,6) not null,
    tax_amount              numeric(20,6) not null,
    exemption_reason_code   text,
    rule_reference          text,
    unique (invoice_id, tax_category, tax_rate, exemption_reason_code)
);

create table vat_transaction (
    transaction_id          uuid primary key,
    invoice_id              uuid not null unique references invoice(invoice_id),
    supplier_taxpayer_id    uuid not null references taxpayer(taxpayer_id),
    customer_taxpayer_id    uuid references taxpayer(taxpayer_id),
    transaction_type        text not null check (transaction_type in ('SALE','PURCHASE','IMPORT','ADJUSTMENT','REVERSAL')),
    tax_point_date          date not null,
    currency_code           char(3) not null,
    taxable_amount          numeric(20,6) not null,
    vat_amount              numeric(20,6) not null,
    status                  text not null check (status in ('POSTED','PARTIALLY_REVERSED','REVERSED')),
    rule_set_version        text not null,
    posted_at               timestamptz not null,
    created_at              timestamptz not null
);

create table tax_period (
    tax_period_id           uuid primary key,
    taxpayer_id             uuid not null references taxpayer(taxpayer_id),
    period_type             text not null,
    period_start            date not null,
    period_end              date not null,
    filing_due_date         date,
    status                  text not null check (status in ('OPEN','CLOSING','CLOSED','FILED','REOPENED')),
    created_at              timestamptz not null,
    updated_at              timestamptz not null,
    check (period_end >= period_start),
    unique (taxpayer_id, period_start, period_end)
);

create table vat_ledger_entry (
    ledger_entry_id         uuid primary key,
    transaction_id          uuid not null references vat_transaction(transaction_id),
    taxpayer_id             uuid not null references taxpayer(taxpayer_id),
    tax_period_id           uuid references tax_period(tax_period_id),
    account_code            text not null check (account_code in ('OUTPUT_VAT','INPUT_VAT','IMPORT_VAT','VAT_CONTROL','ADJUSTMENT','CARRY_FORWARD','REFUND_CONTROL')),
    entry_type              text not null check (entry_type in ('DEBIT','CREDIT')),
    amount                  numeric(20,6) not null check (amount >= 0),
    currency_code           char(3) not null,
    tax_rate                numeric(9,6),
    source_type             text not null,
    source_id               uuid not null,
    reversal_of_entry_id    uuid references vat_ledger_entry(ledger_entry_id),
    status                  text not null check (status in ('POSTED','REVERSED')),
    posted_at               timestamptz not null,
    created_at              timestamptz not null
);

create index vat_ledger_taxpayer_period_idx on vat_ledger_entry(taxpayer_id, tax_period_id, account_code);
create index vat_ledger_transaction_idx on vat_ledger_entry(transaction_id);

create table certificate (
    certificate_id          uuid primary key,
    invoice_id              uuid not null unique references invoice(invoice_id),
    transaction_id          uuid not null unique references vat_transaction(transaction_id),
    certificate_status      text not null check (certificate_status in ('VALID','REVERSED','REVOKED')),
    invoice_hash            bytea not null,
    signature_algorithm     text not null,
    signing_key_id          text not null,
    signature_value         text not null,
    verification_token_hash bytea not null unique,
    certified_at            timestamptz not null,
    revoked_at              timestamptz,
    revocation_reason       text
);

create table match_result (
    match_result_id         uuid primary key,
    transaction_id          uuid not null references vat_transaction(transaction_id),
    seller_invoice_id       uuid not null references invoice(invoice_id),
    buyer_invoice_id        uuid references invoice(invoice_id),
    match_status            text not null check (match_status in ('MATCHED','PARTIAL','UNMATCHED','CONFLICT','NOT_APPLICABLE')),
    match_method            text not null,
    confidence_score        numeric(5,4) check (confidence_score between 0 and 1),
    difference_taxable      numeric(20,6) not null default 0,
    difference_vat          numeric(20,6) not null default 0,
    decision_evidence       jsonb not null,
    decided_at              timestamptz not null,
    supersedes_match_id     uuid references match_result(match_result_id),
    created_at              timestamptz not null
);

create index match_result_transaction_idx on match_result(transaction_id, decided_at desc);

create table exception_case (
    exception_id            uuid primary key,
    exception_number        text not null unique,
    taxpayer_id             uuid not null references taxpayer(taxpayer_id),
    transaction_id          uuid references vat_transaction(transaction_id),
    match_result_id         uuid references match_result(match_result_id),
    exception_type          text not null,
    severity                text not null check (severity in ('LOW','MEDIUM','HIGH','CRITICAL')),
    status                  text not null check (status in ('OPEN','UNDER_REVIEW','RESPONDED','RESOLVED','REJECTED','ESCALATED','CLOSED')),
    owner_user_id           uuid,
    due_at                  timestamptz,
    resolution_code        text,
    resolution_summary     text,
    opened_at               timestamptz not null,
    resolved_at             timestamptz,
    created_at              timestamptz not null,
    updated_at              timestamptz not null
);

create table rule_set (
    rule_set_id             uuid primary key,
    rule_set_code           text not null,
    semantic_version        text not null,
    effective_from          timestamptz not null,
    effective_to            timestamptz,
    status                  text not null check (status in ('DRAFT','APPROVED','ACTIVE','RETIRED')),
    approved_by             uuid,
    approved_at             timestamptz,
    source_authority        text not null,
    content_hash            bytea not null,
    created_at              timestamptz not null,
    unique (rule_set_code, semantic_version)
);

create table tax_rule (
    rule_id                 uuid primary key,
    rule_set_id             uuid not null references rule_set(rule_set_id),
    rule_code               text not null,
    rule_type               text not null,
    priority                integer not null,
    expression_language     text not null,
    expression              jsonb not null,
    explanation_template    text not null,
    test_pack_reference     text not null,
    created_at              timestamptz not null,
    unique (rule_set_id, rule_code)
);

create table vat_return (
    vat_return_id           uuid primary key,
    taxpayer_id             uuid not null references taxpayer(taxpayer_id),
    tax_period_id           uuid not null references tax_period(tax_period_id),
    version                 integer not null,
    status                  text not null check (status in ('DRAFT','UNDER_REVIEW','APPROVED','SUBMITTED','ACCEPTED','REJECTED','AMENDED')),
    ledger_cutoff_at        timestamptz not null,
    rule_set_version        text not null,
    output_tax              numeric(20,6) not null,
    input_tax               numeric(20,6) not null,
    adjustments             numeric(20,6) not null,
    amount_due_or_refundable numeric(20,6) not null,
    calculation_evidence    jsonb not null,
    submitted_at            timestamptz,
    external_submission_id  text,
    created_at              timestamptz not null,
    updated_at              timestamptz not null,
    unique (taxpayer_id, tax_period_id, version)
);

create table risk_alert (
    risk_alert_id           uuid primary key,
    taxpayer_id             uuid not null references taxpayer(taxpayer_id),
    transaction_id          uuid references vat_transaction(transaction_id),
    vat_return_id           uuid references vat_return(vat_return_id),
    model_or_rule_version   text not null,
    risk_type               text not null,
    risk_score              numeric(6,5) check (risk_score between 0 and 1),
    risk_band               text not null check (risk_band in ('LOW','MEDIUM','HIGH','CRITICAL')),
    reason_codes            jsonb not null,
    explanation             text not null,
    status                  text not null check (status in ('OPEN','ACKNOWLEDGED','DISMISSED','REFERRED','CLOSED')),
    created_at              timestamptz not null,
    updated_at              timestamptz not null
);

create table audit_case (
    audit_case_id           uuid primary key,
    case_number             text not null unique,
    taxpayer_id             uuid not null references taxpayer(taxpayer_id),
    tax_period_id           uuid references tax_period(tax_period_id),
    case_type               text not null,
    status                  text not null check (status in ('OPEN','PLANNING','EVIDENCE_COLLECTION','TAXPAYER_RESPONSE','DECISION','APPEAL','CLOSED')),
    lead_auditor_user_id    uuid,
    opened_reason           text not null,
    opened_at               timestamptz not null,
    closed_at               timestamptz,
    created_at              timestamptz not null,
    updated_at              timestamptz not null
);

create table offline_device (
    offline_device_id       uuid primary key,
    device_code             text not null unique,
    taxpayer_id             uuid not null references taxpayer(taxpayer_id),
    source_system_id        uuid not null references source_system(source_system_id),
    certificate_thumbprint  text not null unique,
    status                  text not null check (status in ('PENDING','ACTIVE','SUSPENDED','REVOKED','LOST')),
    last_sequence           bigint not null default 0,
    last_batch_hash         bytea,
    enrolled_at             timestamptz not null,
    last_sync_at            timestamptz
);

create table offline_batch (
    offline_batch_id        uuid primary key,
    offline_device_id       uuid not null references offline_device(offline_device_id),
    sequence_from           bigint not null,
    sequence_to             bigint not null,
    previous_batch_hash     bytea,
    batch_hash              bytea not null,
    signature_value         text not null,
    status                  text not null check (status in ('RECEIVED','VALIDATED','PARTIAL','REJECTED','COMPLETED')),
    received_at             timestamptz not null,
    completed_at            timestamptz,
    check (sequence_to >= sequence_from),
    unique (offline_device_id, sequence_from, sequence_to),
    unique (batch_hash)
);

create table idempotency_record (
    idempotency_record_id   uuid primary key,
    client_id               uuid not null,
    operation_code          text not null,
    idempotency_key_hash    bytea not null,
    request_hash            bytea not null,
    response_status         integer,
    response_reference_id   uuid,
    state                   text not null check (state in ('IN_PROGRESS','COMPLETED','FAILED_RETRYABLE')),
    expires_at              timestamptz not null,
    created_at              timestamptz not null,
    updated_at              timestamptz not null,
    unique (client_id, operation_code, idempotency_key_hash)
);

create table outbox_event (
    outbox_event_id         uuid primary key,
    aggregate_type          text not null,
    aggregate_id            uuid not null,
    event_type              text not null,
    event_version           integer not null,
    partition_key           text not null,
    payload                 jsonb not null,
    occurred_at             timestamptz not null,
    published_at            timestamptz,
    publish_attempts        integer not null default 0,
    last_error              text
);

create index outbox_unpublished_idx on outbox_event(occurred_at) where published_at is null;

create table audit_event (
    audit_event_id          uuid primary key,
    occurred_at             timestamptz not null,
    actor_type              text not null check (actor_type in ('USER','SERVICE','DEVICE','SYSTEM')),
    actor_id                text not null,
    action                  text not null,
    resource_type           text not null,
    resource_id             text not null,
    taxpayer_scope_id       uuid,
    correlation_id          uuid,
    source_ip_token         text,
    outcome                 text not null check (outcome in ('SUCCESS','DENIED','FAILED')),
    reason_code             text,
    before_hash             bytea,
    after_hash              bytea,
    evidence_reference      text,
    event_hash              bytea not null,
    previous_event_hash     bytea,
    details                 jsonb not null
);

create index audit_event_resource_idx on audit_event(resource_type, resource_id, occurred_at);
create index audit_event_actor_idx on audit_event(actor_type, actor_id, occurred_at);

comment on table audit_event is 'Append-only security and business audit evidence; application roles receive INSERT/SELECT only through controlled interfaces.';
comment on table vat_ledger_entry is 'Append-only double-entry VAT sub-ledger. Production posting procedure must enforce balanced entries per transaction and currency.';
comment on table outbox_event is 'Transactional outbox committed with aggregate changes; publisher marks published_at after broker acknowledgement.';

