import type { Metadata } from "next";
import { AppShell } from "@/components/AppShell";
import { PageHeader, StatusBadge } from "@/components/PageHeader";
import { getCurrentUser, requirePermission } from "@/lib/auth";
import { getPlatformSnapshot } from "@/lib/data/platform-repository";
import { formatDateTime } from "@/lib/format";

export const metadata: Metadata = { title: "Integrations and platform health" };
export const dynamic = "force-dynamic";

export default async function IntegrationsPage() {
  const user = await getCurrentUser(); requirePermission(user, "integrations:read"); const data = await getPlatformSnapshot(user);
  return <AppShell active="integrations" permission="integrations:read"><PageHeader eyebrow="Platform ecosystem" title="Integration contracts and operational health" description="Each external capability has an explicit contract, credential reference, configuration state and health outcome. Missing authority or banking agreements remain disabled rather than simulated." />
    <section className="metric-grid"><article className="metric"><div className="metric-top"><span className="metric-label">Connections</span><span className="metric-icon">I</span></div><div className="metric-value">{data.integrations.length}</div><div className="metric-foot">Government, banking and payment boundaries</div></article><article className="metric"><div className="metric-top"><span className="metric-label">Configured</span><span className="metric-icon">C</span></div><div className="metric-value">{data.integrations.filter((item) => item.configuration_status === "CONFIGURED").length}</div><div className="metric-foot">Ready for governed execution</div></article><article className="metric"><div className="metric-top"><span className="metric-label">Blocked jobs</span><span className="metric-icon">B</span></div><div className="metric-value">{data.syncJobs.filter((item) => String(item.status).includes("BLOCKED")).length}</div><div className="metric-foot warning">External setup required</div></article><article className="metric"><div className="metric-top"><span className="metric-label">Outbox pending</span><span className="metric-icon">E</span></div><div className="metric-value">{Number(data.outbox.find((item) => item.status === "PENDING")?.count ?? 0)}</div><div className="metric-foot">Durable events awaiting publisher</div></article></section>
    <section className="panel"><div className="panel-head"><div><h2 className="panel-title">Integration registry</h2><div className="panel-meta">No credentials are stored in application tables</div></div></div><div className="table-wrap"><table><thead><tr><th>Provider</th><th>Category</th><th>Capabilities</th><th>Configuration</th><th>Operations</th><th>Classification</th><th>Health</th></tr></thead><tbody>{data.integrations.map((item) => <tr key={String(item.id)}><td><strong>{String(item.display_name)}</strong><div className="mono muted">{String(item.provider_key)}</div></td><td>{String(item.category)}</td><td className="mono">{String(item.capabilities)}</td><td><StatusBadge value={String(item.configuration_status)} /></td><td><StatusBadge value={String(item.operational_status)} /></td><td>{String(item.data_classification)}</td><td>{item.last_health_check_at ? formatDateTime(String(item.last_health_check_at)) : "Not checked"}</td></tr>)}</tbody></table></div></section>
    <section className="panel" style={{ marginTop: 20 }}><div className="panel-head"><div><h2 className="panel-title">Service component posture</h2><div className="panel-meta">Readiness is capability-specific, not one global green light</div></div></div><div className="table-wrap"><table><thead><tr><th>Component</th><th>Type</th><th>Criticality</th><th>Configuration</th><th>Operational status</th><th>Dependency</th><th>Detail</th></tr></thead><tbody>{data.components.map((item) => <tr key={String(item.id)}><td><strong>{String(item.display_name)}</strong></td><td>{String(item.component_type)}</td><td><StatusBadge value={String(item.criticality)} /></td><td><StatusBadge value={String(item.configuration_status)} /></td><td><StatusBadge value={String(item.operational_status)} /></td><td>{String(item.dependency_summary)}</td><td>{String(item.status_detail)}</td></tr>)}</tbody></table></div></section>
  </AppShell>;
}
